const fs = require('fs');
const path = require('path');

const ROOT = __dirname;

function escapeForTemplate(str) {
  return str
    .split('\\').join('\\\\')
    .split('`').join('\\`')
    .split('${').join('\\${');
}

// Read the HTML source if it exists, otherwise create a basic template
const htmlPath = path.join(ROOT, 'index.html');
if (!fs.existsSync(htmlPath)) {
  fs.writeFileSync(htmlPath, '<!DOCTYPE html><html><head><title>Personal LMS</title></head><body><h1>Personal LMS</h1></body></html>', 'utf8');
}

let html = fs.readFileSync(htmlPath, 'utf8');
html = escapeForTemplate(html);

const htmlOutput = `// Auto-generated by build.js — do not edit directly
export const HTML_TEMPLATE = \`${html}\`;
`;

fs.writeFileSync(path.join(ROOT, 'html.js'), htmlOutput, 'utf8');
console.log('Generated html.js');

// Service worker
const swPath = path.join(ROOT, 'sw.js');
if (!fs.existsSync(swPath)) {
  fs.writeFileSync(swPath, "const CACHE_NAME = 'lms-cache-v1';\nself.addEventListener('fetch', e => {});", 'utf8');
}

let swJs = fs.readFileSync(swPath, 'utf8');
swJs = escapeForTemplate(swJs);

const swOutput = `// Auto-generated by build.js — do not edit directly
export const SW_CONTENT = \`${swJs}\`;
`;

fs.writeFileSync(path.join(ROOT, 'sw-content.js'), swOutput, 'utf8');
console.log('Generated sw-content.js');
